name: Bug Report
description: Create a report to help us improve GarrisonOS
title: "fix: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue! Please ensure that security vulnerabilities are NOT reported here (see [SECURITY.md](SECURITY.md)).
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Execute '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Node.js version, PHP version, OS, etc.
      placeholder: "Node.js 22.5.0, PHP 8.2, Ubuntu 24.04"
    validations:
      required: false
